version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.10.1
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.10.1
    hostname: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    image: logstash:7.10.1
    hostname: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
      - "8080:8080"
    volumes:
      - ./logstash/logstash.conf:/opt/logstash/pipeline/logstash.conf
